QUOTES = [
    "„Bayern ist das bessere Deutschland.“",
    "„Der Einfluss der Freien Wähler in Berlin ist genauso groß wie auf dem Mond.“",
    "„Corona ist wie ein Tsunami.“",
    "„Ich sehe mich nicht als Kanzlerkandidat.“",
    "„Wir bleiben stabil.“",
    "„Ich bin ein großer Fan von Star Wars.“",
    "„Wissen Sie, was das schönste an Berlin ist? Der Weg zurück nach Bayern.“",
    "„Weihnachten bemisst sich offenkundig dieses Jahr nicht in dem Wert von Konsum und Geschenken. Vielleicht sollten wir jetzt mal reflektieren, dass das tollste Geschenk Gesundheit und Gemeinsamkeit ist.“",
    "„Das ganze Leben ist ein großer Kompromiss, das fängt bei der Ehe an und endet in der Politik.“",
    "„Wir machen in Bayern grüne Politik, aber wir brauchen die Grünen nicht dazu.“",
    "„Ehrfürchtig gedenke ich des Lebens und des Vermächtnisses von Mahatma Gandhi.“",
    "„Wir wollen, dass München ein echtes Tennismekka, eine Tennishauptstadt wird.“",
    "„Ich freue mich jetzt mal auf eine Schweinshaxe, bald wieder.“",
    "„Jetzt gibt es wieder Leberkäs statt Tofu-Tümelei.“",
    "„Wir hatten mal Zeit zum Reden, aber auch zum Nachdenken.“",
    "„Wir werden Deutschland nicht blamieren, im Gegenteil.“",
    "„Ich möchte, dass man in Bayern gut leben kann.“",
    "„Weil jeder blöde Krempel, den ich wissen will, den weiß ChatGPT.“",
    "„Wir sind da so ein bisschen das Kalifornien von Deutschland.“",
    "„München ist Surferparadies, und dieses Surfen passt zu Bayern dazu - leben und leben lassen.“",
    "„Ich sehe ihn als einen James Dean von Bayern.“",
    "„Das Kreuz gehört zu Bayern.“",
    "„Wien ist näher bei München als Berlin.“",
    "„Natürlich gilt: Niemand ist gezwungen, Fleisch zu essen. Jeder darf essen, was er will. Aber für mich persönlich gilt: Ein gegrilltes Stück Schweinefleisch aus bayerischer Herkunft ist einfach unschlagbar.“",
    "„Ich esse auch gern Salat und gesunde Sachen. Die meisten Likes gibt es aber dann doch bei sehr bodenständigem bayerischen Essen.“",
    "„Als Kind waren meine beiden absoluten Top-Essen Nürnberger Rostbratwürste oder ein Hendl. Die gab es immer als Belohnung. Für Nürnberger Rostbratwürste könnte ich sterben. Und ein Hendl mit Pommes und Ketchup, das war als Kind schon etwas Besonderes.“",
    "„Es ist übrigens gut, dass Friedrich Merz jetzt Kanzler ist, denn bei Olaf Scholz war das Essen im Kanzleramt nicht immer nach meinem Geschmack. Oft gab es zum Beispiel eine sehr dünne und fade Gemüsesuppe. Bei Angela Merkel gab es immer tolles und auch deftiges Essen: dicke Fleischpflanzerl, Kotelett, Wiener Würstchen...“",
    "„Bei einem Besuch bei ihm in Baden-Württemberg gab's das größte Stück Fleisch, das je ein Grüner vor meinen Augen gegessen hat.“",
    "„Tofu schmeckt einfach furchtbar, im Grunde nach gar nichts.“",
    "„Bei Eis kann ich schlecht Nein sagen. Spaghettieis ist eine grandiose deutsche Erfindung. Ich esse auch oft Pistazie, Malaga oder Erdbeere. Das Eissandwich ist auch super. Da esse ich immer erst Schoko, weil das am wenigsten schmeckt, dann Vanille, dann Erdbeere.“",
    "„Ich versuche auf jeden Fall, auf mein Gewicht zu achten, und mache deshalb auch viel Sport, sooft es mein Kalender zulässt.“",
    "„Eine Kindheit ohne Gelbwurst oder ohne Leberkäse, da fehlt doch was...“",
    "„Die EU gefährdet jeden Tag meine Gesundheit, indem sie die Plastikdeckel an den Flaschen befestigt hat. Jeden Tag hängt mir der Plastikdeckel im Auge, wenn ich meine Cola light trinke.“",
    "„Das Kreuz gehört zu Bayern.“"
    

]